spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookingpj?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Son.ymmm.140899

  jpa:
    show-sql: false
    properties:
      hibernate:
        use-new-id-generator-mappings: false
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 2000
        order_inserts: true
        order_update: true
    open-in-view: false
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy/MM/dd HH:mm
  liquibase:
    change-log: classpath:/liquibase/db-changelog-master.xml
    enabled: true
    drop-first: false
